### ISSUE TITLE
No order tracking on the success page

### ISSUE THREAD

**Issue by MHEGERM** [magepal/magento2-googletagmanager#15]
Hello,

First of all thank you for this great plugin.

I could install it successfully and the code snippet is installed on all pages. Only I saw during a test order that here the orders tracking code is not taken / is displayed.
Only the following is installed in the source code:

<script>
window.dataLayer = window.dataLayer || [];
dataLayer.push({"pageType":"checkout_cart_index","list":"other","customer":{"isLoggedIn":true,"id":"3","groupId":"1"},"cart":{"hasItems":false},"ecommerce":{"currencyCode":"EUR"}});

</script>

<noscript><iframe src="//www.googletagmanager.com/ns.html?id=XXX-XXXXXXX"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','XXX-XXXXXXX');</script>

Do I have to make any settings here or do you have any advice for fixing the problem?

Many thanks and best regards

**Comment by srenon** [comment]
The "pageType" is "checkout_cart_index" therefore you are on the cart page.

I think what you are doing wrong is trying to view page source which will redirect you to in cart page because since the session has expired for you to view the success page

To test in chrome browser you need to https://developers.google.com/web/tools/chrome-devtools/inspect-styles/ then search for the tag or using something like https://chrome.google.com/webstore/detail/tag-assistant-by-google/kejbdjndbnbjgmefkgdddjlbokphdefk?hl=en

**Comment by MHEGERM** [comment]
Oh, you're right, sorry.

Everything is tracked.
Thanks again

**Comment by Serge-Wiki** [comment]
Hi guys, maybe you could help. I’m new to GTM integration and would like to create Event for E-commerce tracking, but cant find the event name which I could use to create a custom trigger.
Is my module working correct, or do I do something wrong?
![gtm](https://user-images.githubusercontent.com/31511015/29962142-b7dfea00-8f0a-11e7-9653-289a61709db4.png)
